### ISSUE TITLE
Self-Signed Certificate

### ISSUE THREAD

**Issue by TheOneValen** [docspell/dsc#104]
Hi!

Currently I cannot use dsc due to my instance using a certificate signed by a private PKI. I Added the root to my system wide trust store (curl and stuff all works) but dsc won't. 

Which trust store does the client use?

I also propose an option to provide the key via cli (and/or config.toml) for folks, that use self-signed certs without PKI.

Have a nice day!

**Comment by eikek** [comment]
Oh, good question! What package do you use - the ones from the release page? If so they are built using rustls, This may have their own strategy regarding trust stores. I couldn't find anything useful from a quick search. Might be that you need to build it yourself and try things out. For example, you could build it on your machine linking it against openssl - this should then use your systems trust store. 

Another try might be building with the feature `rustls-tls-native-roots`, like using this line in `Cargo.toml`: 
```
[features]
…
rustls = ["reqwest/rustls-tls", "rustls-tls-native-roots"]
```
When using rustls, [this crate](https://github.com/rustls/rustls-native-certs) seems to integrate the systems trust-store with rustls, which is mentioned in the [docs](https://docs.rs/reqwest/0.11.9/reqwest/#optional-features) of the reqwest library. If that would work, we can add it to subsequent builds.

The last point, I'm not sure I understand: is it good enough if the tool is using the system trust store or do you want an option to specify your root certificate directly?

**Comment by TheOneValen** [comment]
An option to specify the certificate would be the most flexible option. I would guess that people using their own certificate mostly don't have a whole PKI setup.

I'll look into what the library you use, uses as store, thanks for the hint.

26.01.2022 21:18:54 eikek ***@***.***>:

**Comment by TheOneValen** [comment]
Sorry for my delayed reply. Is this already in an official release or should I test it from some nightly?

**Comment by eikek** [comment]
No worries! It is already in the current release, there is a `--extra-certificate` global option.

**Comment by TheOneValen** [comment]
Works like a charm! I just cannot get it to work using the `.toml`, have to use the cli option. Is this intended?

**Comment by eikek** [comment]
Oh right - that is simply not done! But it should be…. I think the proxy settings and certificate are good to have in the config. Needs a new issue.
