### ISSUE TITLE
Content-Lenght:0 for empty POST requests required by some httpd

### ISSUE THREAD

**Issue by nekrondev** [docspell/dsc#227]
Some http-servers like IIS or Lighttpd require a "Content-Lenght:0" http header to fulfill a POST request  with empty body (or else you will receive a http 411 status code telling you that the content lenght is missing).

This is for example when re-creating the Solr index `dcs admin -a xxxx recreate-index`.

```
~/docker/docspell$ ./dsc admin -a secret recreate-index
Cmd: Admin: RecreateIndex: An http error occurred: An error was received from https://myserver.com/api/v1/admin/fts/reIndexAll: HTTP status client error (411 Length Required) for url (https://myserver.com/api/v1/admin/fts/reIndexAll)
```

**Comment by eikek** [comment]
Thanks for reporting this. To me this behavior is really strange… but it's easier to change `dsc` 😄
