### ISSUE TITLE
Watch option with --exclude

### ISSUE THREAD

**Issue by mp68** [docspell/dsc#27]
Hi,
I'm not sure where to put the --exclude option when running dsc with the watch option. Right now I'm using:
`dsc -d http://docspell-restserver:7880 watch --delete -ir --header Docspell-Integration:xyz /opt/docs --exclude *@SynoEAStream`
but I'm getting this error message
```
error: Found argument '--exclude' which wasn't expected, or isn't valid in this context
If you tried to supply `--exclude` as a PATTERN use `-- --exclude`
USAGE:
dsc watch <dirs>... --delete --integration --recursive --header <header>
For more information try --help

```
Obviously `-- --exclude` is not a valid option, but how can I use it?

**Comment by eikek** [comment]
Right, the `--exclude` option is not there. I think you want the `--not-matches` option, which is the counterpart to the `--matches` option. You can see all possible options and some explanation with `--help`, like `dsc watch --help`

**Comment by mp68** [comment]
Great, thanks a lot!
