### ISSUE TITLE
Only support the date from 2010, what about the older files？

### ISSUE THREAD

**Issue by iszhi** [docspell/dsc#304]
I'm going to move my saved documents into Docspell. Recently I found that it only allows me to set the file date from 2010. But what about the older files?

**Comment by eikek** [comment]
Hi @iszhi again asking if this is supposed to be in the docspell project? But even with this in mind, I'm not really understanding the issue. What is preventing you to send older files?

**Comment by iszhi** [comment]
@eikek See here. When I want to select a date for a file. The oldest date I can set is 2010. 
![image](https://user-images.githubusercontent.com/33443222/230716737-c0ff1f11-6b76-4fb9-af5e-018fed47c0c5.png)
But I'm not sure if this is the correct place for my question. I'm using docspell docker instance.
