### ISSUE TITLE
Didn't show All Folders in the list

### ISSUE THREAD

**Issue by iszhi** [docspell/dsc#305]
I'd like to set up several folders, and assign new files in diffrent dolders. When I want to search them, I'll filter them according to different folders. However, it didn't list all folders I have, but only show me 1 folder. I think that this is a bug that we can improve in the future version.

**Comment by eikek** [comment]
HI @iszhi could it be that you wanted to raise this in the docspell project? This is dsc, the command line client - or do I miss something?

**Comment by iszhi** [comment]
@eikek I see. I'm going to find the right place.
