### ISSUE TITLE
Let nix users specify the rust platform?

### ISSUE THREAD

**Issue by antifuchs** [docspell/dsc#35]
Integrating dsc in my nix flake (which forces users to pin all revisions of all software), I get an error:

```
error: in pure evaluation mode, 'fetchTarball' requires a 'sha256' argument
```

which I'm tracing back to https://github.com/docspell/dsc/blob/master/nix/rust-platform.nix#L3-L4, where fetchTarball is invoked in a way that prevents hermetic encapsulation. I think it's fine to provide this as a default for non-pinned builds, but it would be very nice if we were able to override the rustPlatform argument to the package.

**Comment by antifuchs** [comment]
Oh, similarly, I think it would be great if the nixos module provided here also allowed giving a `package` argument (with a default) and used that in https://github.com/docspell/dsc/blob/master/nix/module.nix#L130!

**Comment by eikek** [comment]
Thank you! Yes sure, good ideas! I'm open for every improvement. I just added what is necessary to work for me :-)
