### ISSUE TITLE
FR: when filesystem backend is used: export symlinks only

### ISSUE THREAD

**Issue by madduck** [docspell/dsc#374]
I am coming from Paperless-NGX, which maintains all documents on the filesystem, rather than the database. As a consequence, the developers made the actual storage location configurable for each document type, and named this concept [Storage Paths](https://docs.paperless-ngx.com/advanced_usage/#storage-paths).

We've been using storage paths to export views into the DMS as read-only Samba shares, such that people could actually browse the DMS content with Windows Explorer, and find e.f. invoices sorted by year under `\Invoices\2023\some_file_title.pdf`. This made the migration to Paperless a lot easier since existing habits and tools didn't need to be changed right away, or at least not completely.

With Docspell, it occurs to me that almost the same can be achieved using `dsc export` run by Cron at regular intervals. However, depending on the size of the documents in the system, this could be quite a cruel process on the disk/SSD and system in general.

If the filesystem backend is already used, and the system on which `dsc` runs has access to the storage, then the data are already accessible on disk. Wouldn't it be conceivable for the API to then just return paths instead of file content, and `dsc` to symlink the existing files?

Obviously, they must not be modified, and this would be within the realm of the administrator to ensure. Here Be Dragons…

**Comment by eikek** [comment]
I'm sorry, but I don't like that at all 😄. It doesn't fit the design. That is one consequence of the decoupling of docspells components. Nothing in docspell knows about the filesystem (except the code that wries and reads there). Handing this information anywhere is a hack in my eyes and will inevitably lead to lots of issues (not only in the code; and they come up here then :)). Also, docspell can be scaled out, which is a bit of a pain when using a file system. Lastly, there is no indication, that the machine with storage is the same as the machine running the restserver(s) and the machines running the joex(es). They can all be different. This could only work for one single deployment scenario.

The `dsc export` is made for that use case. I also have a samba share of a view to the files. The `dsc export` can be used to either export all or a portion of the data (you can define a query). Samba presents symlinks as directories. With the export opitons you can define alternative symlink trees that won't add to the disk usage, but can be accessed by samba as if they were real files and directories. This way multiple views to the documents are possible to create. Depending on the schedule, it is a few minutes off.

I think I wrote somewhere, that it is possible (of course) to get the path into your filesystem given the item id. If people want to do it, they can write a one-line bash script. Then you can use the search and not download anything. I wouldn't recommend, but I'm happy to assist here if needed.

**Comment by madduck** [comment]
I think https://github.com/eikek/docspell/issues/2270 is the right way to go anyway.
