### ISSUE TITLE
Failure when using doc upload

### ISSUE THREAD

**Issue by r4tze** [docspell/dsc#49]
When I tray to upload documents with the doc tool, I get the following error:
```
Cmd: Upload: An http error occurred: Session error: Error reading session file at /home/doc-user/.config/dsc/dsc-token.json: No such file or directory (os error 2)!
```

This is, what the .config/dsc/config.toml looks like:
```
docspell_url = "http://localhost:7880"
default_format = "Tabular"
pdf_viewer = ["zathura", "{}"]
```
Am I missing something? I also tried it with the following entry in the toml:
```
default_account = "COLLECTION\username"
```
But I still get the same error.

**Comment by eikek** [comment]
Can you show me the command you are executing?

The error message means that you are not logged in. But this is not necessary for uploading, if you choose the integration endpoint or when you use a "source url" as described [here](https://docspell.org/docs/webapp/uploading/#anonymous-upload). You then need to specify the "source id" in the config file via `default_source_id = "<some sorce id>"`. If you don't use any of the above, then the tool wants you to be logged in. You can do this via the `dsc login` command.

**Comment by r4tze** [comment]
I found my mistake. I had to change the url from“localhost“ to my IP address. Now everything runs fine.
