### ISSUE TITLE
exclude subfolders from watched folder

### ISSUE THREAD

**Issue by sir-andreas** [docspell/dsc#57]
Hi,

would it be possible to add a command line option to exclude certain subfolders or patterns from beeing considered for an upload? Backgroud for this request is, that sometimes sum index programs create certain files or folders in my consume directoy which confuse the watch deamon. 

Best regards,
Andreas

**Comment by eikek** [comment]
Hi @sir-andreas , would the `--matches` and `--not-matches` option work for you? Not sure if you have seen them, they can be found somewhere in `dsc upload --help`.

**Comment by sir-andreas** [comment]
how do I have to configure the -not-matches option in order to ignore subfolders? I just managed it to ignore files.

**Comment by sir-andreas** [comment]
> how do I have to configure the -not-matches option in order to ignore subfolders? I just managed it to ignore files.

Found it out by myself in the meantime ... anyway, thank you very much for your support and this great piece of software! 👍

**Comment by eikek** [comment]
Ah great! I actually had to look it up, too.  For reference: [this](https://docs.rs/glob/0.3.0/glob/) library is used; you can specify two asterisks `**` - that would match multiple subdirectories.
