### ISSUE TITLE
how to start "dsc watch" with server start

### ISSUE THREAD

**Issue by speedAmaster** [docspell/dsc#59]
I am newbie to docspell and still exploring. looks awesome so far!
I installed by docker-compose
I downloaded "dsc" to the host-system and did a `dsc watch 'my scaninput'`, but obviously this is not started automatically and not demonized.
a) how is it meant to get this run with start of the server?
b) also found that I would have to perform a login regularily as I get an error " Error refreshing session." after a while. how to retain the login?
c) last: could ther files be deleted automatically after being uploaded to docspell?

**Comment by eikek** [comment]
Hi @speedAmaster , thank you! :-)

if you use the docker-compose setup, then there is already a container watching the local `./docs` folder. You don't need to setup this yourself, then. You can change the folder in the docker-compose.yml file (see the `consume-dir` container). So I think this should be enough if you have docker integrated into your system. The container also deletes the uploaded files by default, the `dsc` command accepts a `--delete` flag to the watch or upload command for this. You can see all the possible options with `dsc watch --help`. If you don't use docker, there are many ways to integrate it to start on boot, for example systemd is a popular way today. Hope this answers a) and c). 

For b) this shouldn't happen! The browser should perform a regular request to update the authentication token. Do you see any more errors in the browsers dev console and network tab? Did you change the `base-url` setting in the config file? Also, you could try to click the "remember me" checkbox on login. This will install a cookie that is used to authenticate automatically. You need to allow cookies and local storage for docspell to work (should be by default, if you didn't change this). If you find more error messages or have screenshots, you can post them here if you want.

**Comment by speedAmaster** [comment]
Hi @eikek,
impressive work you did! I am getting to understand your concept better and better!

I tried to locate the ./docs folder but neither
    /home/bernd/docspell/docker/docker-compose/docs
    /home/bernd/docspell/website/site/content/docs
worked.

So I tried changing volumes in docker-compose.yml at
     volumes:
     - /home/bernd/docspell/scaninput:/opt/docs
But didn't work either  - meaning processing the dropped pdf...

Where can I located the ./doc folder?

**Comment by eikek** [comment]
Hi @speedAmaster, I think you are almost there. The line `/home/bernd/docspell/scaninput:/opt/docs` makes your local directory `/home/bernd/docspell/scaninput` available in the container under the path `/opt/docs`. As you can see in `docker-compose.yml`, this folder is passed as argument to the `dsc` tool. But in order for docspell to know for which account to add the dropped document, you must create a subfolder in your `/home/bernd/docspell/scaninput` with the name of the collective you created at registration. Then put the document in this subfolder.

**Comment by speedAmaster** [comment]
Hi @eikek,
you made my day. By adding the folder with name of collective and scanning files into that folder: success! 
Thanks a lot.
PS: as my system is now showing other issue, I will raise another issue here.
